shortDOI support & update environment on 2019-02-06
This build is based on
https://github.com/greenelab/manubot-rootstock/commit/f559600ff1965899b20874e71874794c05787087.

This commit was created by the following Travis CI build and job:
https://travis-ci.org/greenelab/manubot-rootstock/builds/489622322
https://travis-ci.org/greenelab/manubot-rootstock/jobs/489622323

[ci skip]

The full commit message that triggered this build is copied below:

shortDOI support & update environment on 2019-02-06

Merges https://github.com/greenelab/manubot-rootstock/pull/174

* Environment update on 2019-02-06

Does not upgrade weasyprint or cairo, due to the following error during
WeasyPrint execution:
OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2

Specify cairocffi dependency in environment.yml, since v0.9 from PyPI
seemed to trigger the OSError.

* Add shortDOI support & usage

Update repo to https://github.com/manubot/manubot
greenelab/manubot relocated to manubot/manubot as per
https://github.com/manubot/manubot/issues/94.

02.delete-me.md still references greenelab/manubot,
however it is not worth creating merge conflicts to
update just this.