downgrade cairo to 1.14.12
UnsatisfiableError: The following specifications were found to be in conflict:
  - cairo=1.16.0
  - cairocffi=0.8.0 -> cairo=1.14 -> fontconfig=2.12 -> freetype=2.6
  - cairocffi=0.8.0 -> cairo=1.14 -> glib=2.55